apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: translator-frontend
spec:
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: translator-frontend                                  # 6
    spec:
      containers:
        - image: maheshrajannan/translator-frontend:minikube
          imagePullPolicy: Always                         # 7
          name: sa-frontend
          ports:
            - containerPort: 80