apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: translator-frontend
spec:
  replicas: 1                                             # 2
  minReadySeconds: 15
  selector:
    matchLabels:
      app: translator-frontend
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: translator-frontend                                  # 6
    spec:
      containers:
        - image: maheshrajannan/translator-frontend:Minikube
          imagePullPolicy: Always                         # 7
          name: sa-frontend
          ports:
            - containerPort: 80